(** Generated by coq-of-ocaml *)
Require Import OCaml.OCaml.

Local Set Primitive Projections.
Local Open Scope string_scope.
Local Open Scope Z_scope.
Local Open Scope type_scope.
Import ListNotations.

Fixpoint sums (ls : list (list int)) : list int :=
  let fix sum (xs : list int) : int :=
    match xs with
    | [] => 0
    | cons x xs =>
      if equiv_decb x 12 then
        match sums [ [ 13 ] ] with
        | cons x _ => Z.sub x 1
        | _ => 0
        end
      else
        Z.add x (sum xs)
    end in
  match ls with
  | [] => nil
  | cons xs ls => cons (sum xs) (sums ls)
  end.
