(** Generated by coq-of-ocaml *)
Require Import OCaml.OCaml.

Local Set Primitive Projections.
Local Open Scope string_scope.
Local Open Scope Z_scope.
Local Open Scope type_scope.
Import ListNotations.

Parameter t : Set.

Parameter foo : forall {t : Set}, t.

Parameter arg : forall (a b : Set), Set.

Parameter x : forall {a b : Set}, a -> b -> arg a b.

Module M.
  Inductive l : vtag -> Set :=
  | Nil : forall {a : vtag}, l a
  | Cons : forall {a : vtag}, decode_vtag a -> l a -> l a.
  
  Parameter b : bool.
End M.
