(** Generated by coq-of-ocaml *)
Require Import OCaml.OCaml.

Local Set Primitive Projections.
Local Open Scope string_scope.
Local Open Scope Z_scope.
Local Open Scope type_scope.
Import ListNotations.

Inductive t : vtag -> Set :=
| S : int -> t int_tag
| G : t int_tag
| D : string -> t string_tag.

Definition x : t int_tag := S 3.

Definition f (x : t int_tag) : int :=
  match x in t t0 return t0 = int_tag -> int with
  | S x => fun eq0 => ltac:(subst; exact x)
  | G => fun eq0 => ltac:(subst; exact 3)
  | _ => ltac:(discriminate)
  end eq_refl.
